name: flutter_jailbreak_emulator_detection
description: Flutter jailbreak and root detection plugin. This plugin wraps Rootbeer for use on Android and DTTJailbreakDetection for use on iOS. 
version: 1.8.0
homepage: https://github.com/binhlam10796/flutter_jailbreak_detection

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: appmire.be.flutterjailbreakdetection
        pluginClass: FlutterJailbreakDetectionPlugin
      ios:
        pluginClass: FlutterJailbreakDetectionPlugin
